export const SET_PRODUCTS = "SET_PRODUCTS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CART_ADD_ITEM_FAILED = "CART_ADD_ITEM_FAILED";

export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const LIST_MY_ORDER = "LIST_MY_ORDER";
export const LIST_ORDER_FAILED = "LIST_ORDER_FAILED";


